### ISSUE TITLE
Crashes after and entering any URL or search query

### ISSUE THREAD

**Issue by filips123** [cookiengineer/stealth-browser#11]
Stealth crashes after entering any URL or search query. Native URLs (`stealth:`) work.

I tested this with Firefox 68 on Windows and Chrome on Android. Stealth was started in Docker container.

Here are the logs:

```
 (L) Stealth Service Command-Line Arguments:
 (L)
{
    "profile": "/profile",
    "root": "/browser",
    "debug": false
}
 (I) Stealth Service started on http+ws://localhost:65432.
 (I) Stealth Defaults loaded.
 (L) > 379955 blockers, 0 filters, 0 hosts, 0 modes, 0 peers, 0 redirects.
 (I) Stealth Profile loaded from "/profile".
 (L) > 0 blockers, 0 filters, 0 hosts, 0 modes, 0 peers, 0 redirects.
file:///browser/stealth/source/Server.mjs:68
        let session = this.stealth.init(null, request.headers);
                                              ^

ReferenceError: request is not defined
    at Server.handle_request (file:///browser/stealth/source/Server.mjs:68:40)
    at HTTP.receive (file:///browser/stealth/source/Server.mjs:342:22)
    at Object.receive (file:///browser/stealth/source/protocol/HTTP.mjs:593:5)
    at Socket.socket.once (file:///browser/stealth/source/Server.mjs:329:10)
    at Object.onceWrapper (events.js:281:20)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:154:17)
```

**Comment by cookiengineer** [comment]
Hey, thanks for the report.

Took me a while to fix this, because I refactored the Session Management.

The reason is that currently the Browser UI (as in "load via iframe") is broken, and some URLs need to be replaces inside the HTML. So in order to do this, I created the `URL.resolve()` method and some reviews for it:

- [URL Parser](https://github.com/cookiengineer/stealth/blob/X0/stealth/source/parser/URL.mjs)

- [Covert Review for URL Parser](https://github.com/cookiengineer/stealth/blob/X0/covert/review/parser/URL.mjs)

Still broken overall though, as the Session Management needs further work. I'm currently busy building the Sidebar for a Request(s) overview and connected Peers, so that those can be managed more easily (and Peers blocked if they cause too much load).

After that I can start to implement the Optimizer that will re-render (and therefore fix the URLs of resources) the HTML when being requested via iframe.

Using Stealth via Web Proxy should work though for the time being, as parsing, rendering and requesting (of absolute URLs) is done by the external Browser.

**Comment by filips123** [comment]
There are also some other crashes which happen from time to time:


*When opening Stealth URL without `/browser/index.html`:*

```
file:///browser/stealth/source/other/ROUTER.mjs:79
                                path: '/browser/index.html' + (ref.headers['@debug'] ? '?debug' : '')
                                                                          ^

TypeError: Cannot read property '@debug' of null
    at Object.send (file:///browser/stealth/source/other/ROUTER.mjs:79:47)
    at HTTP.receive (file:///browser/stealth/source/Server.mjs:346:14)
    at Object.receive (file:///browser/stealth/source/protocol/HTTP.mjs:593:5)
    at Socket.socket.once (file:///browser/stealth/source/Server.mjs:330:10)
    at Object.onceWrapper (events.js:281:20)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:154:17)
```

*When opening Proxy PAC file:*

```
file:///browser/stealth/source/other/ROUTER.mjs:120
                                url:     'http://' + ref.headers['host'] + '/proxy.pac',
                                                                ^

TypeError: Cannot read property 'host' of null
    at Object.send (file:///browser/stealth/source/other/ROUTER.mjs:120:37)
    at HTTP.receive (file:///browser/stealth/source/Server.mjs:346:14)
    at Object.receive (file:///browser/stealth/source/protocol/HTTP.mjs:593:5)
    at Socket.socket.once (file:///browser/stealth/source/Server.mjs:330:10)
    at Object.onceWrapper (events.js:281:20)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:154:17)
```

**Comment by cookiengineer** [comment]
Are you on the current `X0` branch or on `master`?

The X0 branch is the one I'm working on, and I remember that I thought I had fixed sth. like this a couple weeks ago.

Cross-validation: In the `stealth/source/Server.mjs` there should be a `request.headers['@debug']` entry being set -> https://github.com/cookiengineer/stealth/blob/X0/stealth/source/Server.mjs#L330-L349

Regarding the `headers['host']` entry I'm actually not sure how this can happen. Are you requesting the UI via a domain/ip and via http on port 65432?

If you use the `./bin/browser.sh`, which WebView technology is being used?

**Comment by filips123** [comment]
> Are you on the current `X0` branch or on `master`?

I'm on updated `X0` branch.

> Regarding the `headers['host']` entry I'm actually not sure how this can happen. Are you requesting the UI via a domain/ip and via http on port 65432?

This happens when I try to load Proxy PAC file into Firefox. It also happens when I try to directly open Proxy PAC file in Firefox and Chrome.

> If you use the `./bin/browser.sh`, which WebView technology is being used?

I'm using Docker image. I tested this with Firefox and Chrome.

Something that might be related is, that I'm not accessing UI from `localhost`, but from my other local IP (`http://192.168.64.101:65432/`).

**Comment by cookiengineer** [comment]
Awesome, this is exactly what I needed for reproduction. Confirmed.

**Comment by cookiengineer** [comment]
I think I fixed it now, so that the headers are correct.

You can verify that this is working by requesting the `http://<ip>:65432/proxy.pac` file manually. If there's no `undefined` in there, it's fixed - as it relies on the `Host` header to work.

... so the file contents should look similar to this:

```javascript

function FindProxyForURL(url, host) {
	if (host === "192.168.1.10") return "DIRECT";
	if (host === "localhost") return "DIRECT";
	return "PROXY 192.168.1.10:65432; DIRECT";
}

```

**Comment by filips123** [comment]
Yes, it is fixed.
